[package]
name = "a-rusty-theremin"
version = "0.0.1"
author = "DebuggerDan"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
